version: '3.8'

volumes:
  db-app:
  nosql-app:

services:
  http:
    container_name: http
    image: nginx:mainline
    ports:
    - 8080:80
    - 8443:443
    restart: "no"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - 3001:3000
    restart: on-failure:3
  db:
    image: postgres:16.4
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-app:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # db-adminer:
  #   container_name: db-adminer
  #   image: adminer:4.8.1
  #   ports:
  #     - 8090:8080
  #   restart: unless-stopped
  nosql:
    container_name: nosql
    image: mongo:7.0.8-jammy
    restart: always
    ports:
      - 27017:27017
    env_file: 
      - ./mongo/.env
    volumes:
      - nosql-app:/data/db
  # mongo-express:
  #   container_name:  mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  #     - ME_CONFIG_MONGODB_ADMINURL=mongodb://root:root:27017/
  #cache:
  #messaging: